/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.stetho;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;
import org.appcelerator.titanium.TiApplication;

import com.facebook.stetho.Stetho;


@Kroll.module(name="Stetho", id="ti.stetho")
public class StethoModule extends KrollModule
{

	// Standard Debugging variables
	private static final String LCAT = "StethomoduleModule";
	private static final boolean DBG = TiConfig.LOGD;
	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;

	public StethoModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Stetho.initializeWithDefaults(app.getBaseContext());
		Log.d(LCAT, "Ti.Stetho init");
	}

	// Methods
	@Kroll.method
	public void enableNetwork()
	{
		Log.d(LCAT, "Enabling network inspection");
	}

}
